#
# Economy Main Configuration file.
# Developer(s): [ Nailm, Xanium ]

storage: mysql
vault: true
debug: false
transaction_log: false
mysql:
  database: bungeecord
  prefix: economy
  host: localhost
  port: 3306
  username: minecraft
  password: ''
