#
# GemsEconomy Main Configuration file.
# Developer(s): [ Nailm, Xanium ]

storage: mysql
vault: true
debug: false
transaction_log: false
mysql:
  database: bungeecord
  prefix: gemseconomy
  host: localhost
  port: 3306
  username: minecraft
  password: ''
