#
# GemsEconomy Main Configuration file.
# Developer(s): [ Nailm, Xanium ]

storage: mysql
vault: true
debug: false
transaction_log: false
mysql:
  database: bungeecord
  prefix: gemseconomy
  host: localhost
  port: 3306
  username: minecraft
  password: ''
cheque:
  enabled: false
  material: PAPER
  name: '&a支票'
  lore:
    - '&7价值: {value}.'
    - '&7发行人 {account}'
