name: GemsEconomy
version: ${version}
description: ${description}
main: me.xanium.gemseconomy.GemsEconomy
loader: me.xanium.gemseconomy.GemsEconomyLoader
api-version: 1.19
authors: [ Nailm, other contributors ]
load-before: [ ]
load-after: [ ]
dependencies:
  - name: helper
    required: true
    bootstrap: false
  - name: MewCore
    required: true
    bootstrap: false
  - name: Vault
    required: false
    bootstrap: false
  - name: ConnectorPlugin
    required: false
    bootstrap: false
