name: GemsEconomy
version: ${version}
description: ${description}
main: me.xanium.gemseconomy.GemsEconomy
api-version: 1.19
authors: [ Nailm ]
load-before: [ ]
load-after:
  - name: helper
  - name: MewCore
dependencies:
  - name: helper
    required: true
    bootstrap: false
  - name: MewCore
    required: true
    bootstrap: false
  - name: Vault
    required: false
    bootstrap: false
  - name: ConnectorPlugin
    required: false
    bootstrap: false
