/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

group = "me.xanium.gemseconomy"
version = "1.3.6"
description = "A modern multi-currency economy plugin"

repositories {
    mavenLocal()
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/") {
        content {
            includeGroup("io.papermc.paper")
        }
    }
    maven("https://jitpack.io") {
        content {
            includeGroup("com.github.MilkBowl")
        }
    }
    maven("https://repo.minebench.de") {
        content {
            includeGroup("de.themoep.utils")
            includeGroup("de.themoep.connectorplugin")
        }
    }
    maven("'https://repo.extendedclip.com/content/repositories/placeholderapi/'") {
        content {
            includeGroup("me.clip")
        }
    }
}

dependencies {
    compileOnly("org.jetbrains:annotations:24.0.0")
}